### PR TITLE
2D-distribution

### PR DESCRIPTION
**Pull request by mrava87**
See https://github.com/PyLops/pylops-mpi/issues/113

### CODE REVIEW

**Comment by mrava87** [comment]
@rohanbabbar04 this could do with your review and comments 😄

**Comment by rohanbabbar04** [comment]
> @rohanbabbar04 this could do with your review and comments 😄

I would review this by the end of this week :)

**Comment by rohanbabbar04** [comment]
Sorry,
Give me time till this week
I am onto this...

**Comment by mrava87** [comment]
Any news on this @rohanbabbar04

**Comment by rohanbabbar04** [comment]
I think we should add information about the UNSAFE_BROADCAST in the Warning section of [this page](https://pylops.github.io/pylops-mpi/api/generated/pylops_mpi.DistributedArray.html#pylops_mpi.DistributedArray) to inform users about it. What do you think?

**Comment by mrava87** [comment]
I agree, good point! As we already explain the `BROADCAST`, we can explain that to avoid that behavior one has to use `UNSAFE_BROADCAST` at their own risk (with more responsibility comes higher risk 😜

**Pull request merged**
