### PR TITLE
Added Stacking examples

### PR DESCRIPTION
**Pull request by rohanbabbar04**
- Added `MPIVStack` example(Vertical Stacking).
- Added `MPIHStack` example(Horizontal stacking).
- Added `MPIBlockDiag` example(For Block Diagonal example).

### CODE REVIEW

**Comment by rohanbabbar04** [comment]
For the examples, I have used more than 1 operator(2) at each rank, I think since we use only 1 for our tests, its better to use 2 in the example(plus the plots look better)

**Review by mrava87 — APPROVED** [review]
This looks very good. 

One thing (maybe better to make a separate PR), I would suggest we create an operator called HStack where we just call the VStack matvec/rmatvec in reversed order… code wise it doesn’t add much but users can use it instead of using an adjoint of VStack :) what do you think?

**Comment by mrava87** [comment]
Great, this is good to go :D

**Comment by rohanbabbar04** [comment]
Have changed the example of horizontal stacking with `MPIHStack` instead of `MPIVStack.H`, since it makes more sense and would be easy for users to understand...

**Pull request merged**
