### PR TITLE
doc: added mdd tutorial

### PR DESCRIPTION
**Pull request by mrava87**
This PR adds a new tutorial focused on MDD, replicating part of this tutorial https://pylops.readthedocs.io/en/latest/tutorials/mdd.html#sphx-glr-tutorials-mdd-py with distributed functionalities.

### CODE REVIEW

**Comment by mrava87** [comment]
@rohanbabbar04 I had forgotten to put a tutorial on mdd once I pushed the MPIMDC operator. Since we also mention this problem in our paper, I have gone ahead and added a tutorial now. Have a look and if you agree with it we can merge this PR.

**Comment by mrava87** [comment]
@rohanbabbar04 just checking you saw this :)

**Comment by rohanbabbar04** [comment]
Hi @mrava87 ,
Thanks for this PR...
I will look into this tomorrow

**Comment by rohanbabbar04** [comment]
@mrava87, I think it looks great.

Feel free to merge this PR

**Review by rohanbabbar04 — APPROVED** [review]

**Pull request merged**
