### PR TITLE
🚀 Enable use of cupy arrays

### PR DESCRIPTION
**Pull request by mrava87**
# Motivation
This PR is aimed at extending the capabilities of PyLops-MPI to use of CuPy arrays. This is powered by most of the same routines used in PyLops's CuPy backend.

# Objective
Following https://github.com/PyLops/pylops-mpi/issues/99, we want to explore the combined use of MPI4py and CuPy to allow creating distributed arrays with locals stored on GPUs and direct communication (without passing from CPU). So far, only minimal changes seem to allow this - see notebooks at https://github.com/PyLops/pylops_notebooks/tree/master/developement-mpi/Cupy_MPI

### CODE REVIEW

**Comment by mrava87** [comment]
@rohanbabbar04 I just started to investigate this... so far it seems promising, I plan to do a bit more (at least check that all of the examples can run with cupy arrays) before asking you to have a look and provide your inputs 😄

**Comment by rohanbabbar04** [comment]
> @rohanbabbar04 I just started to investigate this... so far it seems promising, I plan to do a bit more (at least check that all of the examples can run with cupy arrays) before asking you to have a look and provide your inputs 😄

Sure, Let me take a look into this one and also check the examples.

**Comment by rohanbabbar04** [comment]
I think it looks great, you can go ahead and add support for cupy everywhere 
Thanks...

**Comment by mrava87** [comment]
Thanks! I’m trying to handle the last few missing operators and then I can merge it 😀

**Pull request merged**
