### PR TITLE
feat: added MPIFredholm1 and MPIMDC

### PR DESCRIPTION
**Pull request by mrava87**
This PR introduces 2 new operators, namely `MPIFredholm1` and `MPIMDC`, which allow testing the third and last use-case described in the https://github.com/PyLops/pylops/wiki/GSoC-2023-Project-Ideas (e.g., `Both model and data are available in all nodes (or just in the master)`).

Tests are also provided for `MPIFredholm1` and an example is provided for `MPIMDC`

### CODE REVIEW

**Comment by rohanbabbar04** [comment]
Hi @mrava87 , is this ready to be merged??

**Comment by mrava87** [comment]
Yes, I was waiting from any feedback from you :) from my side it is ready to go!

**Comment by rohanbabbar04** [comment]
Thanks!!
Let me take a look into this

**Review by rohanbabbar04 — APPROVED** [review]

**Comment by rohanbabbar04** [comment]
Hi @mrava87 , it looks great !!

You can go ahead and merge this PR.

**Pull request merged**
