### PR TITLE
Made changes to paper.md

### PR DESCRIPTION
**Pull request by rohanbabbar04**
- Changes in `paper.md`

### CODE REVIEW

**Comment by mrava87** [comment]
Sure, I'll try to reduce it further. How do i find out how many words I have after I push the changes?

**Comment by rohanbabbar04** [comment]
Great!!
I see the word count is now close to 960 words which is good. Are you done with the updates?
I will read the paper when you are done and merge this PR

**Comment by mrava87** [comment]
Perfect, yes I am 😀 feel free to re-add back any sentence that may be worth having but we took out to shorten the paper given that we are now 40 words or so below the limit

**Comment by rohanbabbar04** [comment]
> Perfect, yes I am 😀 feel free to re-add back any sentence that may be worth having but we took out to shorten the paper given that we are now 40 words or so below the limit

Great!!,
Let me merge this

**Pull request merged**
